### ISSUE TITLE
[Domains] Add Let's Encrypt fields

### ISSUE THREAD

**Issue by ichbinkour** [Scalingo/scalingo.js#3]

**Comment by johnsudaar** [comment]
The lets_encrypt_status field can take the follwing values:

  - "pending_dns": We're waiting for DNS propagation (or the DNS value is not correct)
  - "new": The certificate request has been sent to LE
  - "created": The Certificate has been created and is in use
  - "dns_required": (wildcards) manual DNS action is required
  - "error": There was an error while creating the certificate.
